### ISSUE TITLE
number service in infobar

### ISSUE THREAD

**Issue by Dima73** [openatv/MetrixHD#224]
If use option "Alternative numbering mode", number service in infobar wrong.
Skin use converter MetrixHDExtServiceInfo.
See example ServiceName2
		elif self.type == self.NUMBER:
			try:
				service = self.source.serviceref
				num = service and service.getChannelNum() or None
			except:
				num = None
			if num:
				return str(num)
			else:
				num, bouq = self.getServiceNumber(ref or eServiceReference(info.getInfoString(iServiceInformation.sServiceref)))
				return num and str(num) or ''

**Comment by atvcaptain** [comment]
that you mean ?

**Comment by Dima73** [comment]
Number service in infobare not correct if use  "Alternative numbering mode".
Just fix it.

**Comment by Dima73** [comment]
@cached
	def getText(self):
		service = self.source.service
		info = service and service.info()
		if not info:
			return ""

		text = ""
		name = info.getName().replace('\xc2\x86', '').replace('\xc2\x87', '')
		try:
			service = self.source.serviceref
			num = service and service.getChannelNum() or None
		except:
			num = None
		if num:
			number = str(num)
		else:
			num = self.getServiceNumber(name, info.getInfoString(iServiceInformation.sServiceref))
			number = num and str(num) or ''
		orbital = self.getOrbitalPosition(info)
		satName = self.satNames.get(orbital, orbital)

**Comment by atvcaptain** [comment]
i cant follow you that must  change and how can see this issue to check that is wrong

**Comment by Dima73** [comment]
Set "Alternative numbering mode" yes.Zap to service number 10 if bouquet two and show infobar.
see service number...

**Comment by atvcaptain** [comment]
thx for the info and fix: https://github.com/openatv/MetrixHD/commit/a0564bdd889e1ab9e28608ecf469fccaa37c9b31
