### ISSUE TITLE
MyMetrixLite plugin other settings 

### ISSUE THREAD

**Issue by jojoz5** [openatv/MetrixHD#346]
Hello! I have activated via MyMetrixLite plugin in other settings Infobar> Show-Extended-Info> yes and after saving changes and restarting the receiver's GUI up above on screen in Infobar appear reception details such as frequency, fec etc as well as channel encryption eg viaccess, irdeto etc. The problem is that the satellite names are old, the fec is sometimes wrong eg 4/5 instead of 3/5, the dvb-s2 channels display as dvb-s and there are not other channel encryptions such as powervu, tandberg. Can this be fixed?
Thanks!

**Comment by iPkay** [comment]
i have changed the converter for the transponder info. channel encryptions - low priority and no idea...
