### ISSUE TITLE
screens are broken !

### ISSUE THREAD

**Issue by thawtes** [openatv/MetrixHD#348]
hi @iPkay 

other settings > Show picons zoomed ? = No

many screens are broken ? e.g. channel list screen plugin list screen and so on.

there is no such problem before pls fix it

my use 1920x1080 FHD

thanks

**Comment by iPkay** [comment]
sorry for that - is fixed: https://github.com/openatv/MetrixHD/commit/3eb855672faea725fa31d0a0ed913c2e9be91efa
