### ISSUE TITLE
translated title not work !

### ISSUE THREAD

**Issue by thawtes** [openatv/MetrixHD#350]
hello @iPkay 

active default skin : epg-import-plugin > the translated title is working (see top in picture)

active MetrixHD skin : epg-import-plugin > the translated title is **not working** (see bottom in picture)

what or where is the problem ?

![issue](http://666kb.com/i/dw7v57mypkqkhzrqb.png "Picture")

**Comment by iPkay** [comment]
Try '<widget source="Title" render="Label"...' instead of '<eLabel text="...'

**Comment by thawtes** [comment]
ok, i got it. thank you.
