### ISSUE TITLE
First Info Bar 

### ISSUE THREAD

**Issue by ozone1864** [openatv/MetrixHD#365]
Dear Captain,
I sent u message on openATV forum,
How to lower the size of the bottom first info bar when changing between channels
and Channel number size ?
Regards,

**Comment by atvcaptain** [comment]
extention menu , mymetrix you can change it

**Comment by ozone1864** [comment]
you mean myMetrixLite configuration ok. But what parameter should be changed ?

**Comment by ozone1864** [comment]
> extention menu , mymetrix you can change it

you mean myMetrixLite configuration ok. But what parameter should be changed ?

**Comment by iPkay** [comment]
The size of infobar can't changed without a skinpart, the size settings from channel number and name is in other settings (mymetrixite)

**Comment by ozone1864** [comment]
ah ok thanks
