### ISSUE TITLE
Your Enhanced HD Settings are inconsistent !

### ISSUE THREAD

**Issue by ozone1864** [openatv/MetrixHD#366]
Hello,
When changing MetrixHD skin resolution from 1280x720 to 1920x1080 HD resolution a popup occurs with following message "Your Enhanced HD Settings are inconsistent !"
Although I the test is successful and atvHD icons downloaded but nothing happens.

**Comment by iPkay** [comment]
you have press green button for save settings and green again for apply settings?

**Comment by iPkay** [comment]
i think now it's ok -https://github.com/openatv/MetrixHD/commit/0d29bbcd100dc4740d2df5a52f4485e20c92d006

**Comment by ozone1864** [comment]
I am using Zgemma h9s

**Comment by ozone1864** [comment]
issue solved
