### ISSUE TITLE
Apply Changes with ...

### ISSUE THREAD

**Issue by thawtes** [openatv/MetrixHD#384]
hello, @iPkay 

I need a command prompt for "Aplly changes"
like this
`python /usr/lib/enigma2/python/Plugins/Extensions/MyMetrixLite/ActivateSkinSettings.pyo`

I do "Aplly changes" with a command prompt?
can you make a mini script for this?

thanks

**Comment by iPkay** [comment]
I think this not possible. (can't import all needed modules outside from e2)
But, if the file exist '/etc/.restore_skins', (https://github.com/openatv/enigma2/blob/6.3/skin.py#L131) then restored your settings on next reboot or gui restart.

**Comment by thawtes** [comment]
> 
> 
> I think this not possible. (can't import all needed modules outside from e2)
> But, if the file exist '/etc/.restore_skins', (https://github.com/openatv/enigma2/blob/6.3/skin.py#L131) then restored your settings on next reboot or gui restart.

this can help thx.

/etc/.restore_skins  how file content should be ?

Should it be as follows?
`config.plugins.MyMetrixLiteColors.channelselectionservicedescription=009A93
config.plugins.MyMetrixLiteColors.channelselectionservicedescriptionselected=1BA1E2
config.plugins.MyMetrixLiteOther.EHDenabled=1
config.plugins.MyMetrixLiteOther.EHDfontoffset=0
config.plugins.MyMetrixLiteOther.EHDpiconzoom=0
config.plugins.MyMetrixLiteOther.EHDtested=vuduo2_|_01
config.plugins.MyMetrixLiteOther.layeraunderlineposy=0
config.plugins.MyMetrixLiteOther.layeraunderlinesize=1`

**Comment by thawtes** [comment]
what i want to do ,
read settings parameter
`config.plugins.MyMetrixLiteColors.channelselectionservicedescription=009A93 config.plugins.MyMetrixLiteColors.channelselectionservicedescriptionselected=1BA1E2 config.plugins.MyMetrixLiteOther.EHDenabled=1 config.plugins.MyMetrixLiteOther.EHDfontoffset=0 config.plugins.MyMetrixLiteOther.EHDpiconzoom=0 config.plugins.MyMetrixLiteOther.EHDtested=vuduo2_|_01 config.plugins.MyMetrixLiteOther.layeraunderlineposy=0 config.plugins.MyMetrixLiteOther.layeraunderlinesize=1`

and write skin file

**Comment by iPkay** [comment]
no content, is a trigger file .if exist will the saved skin settings from '/etc/enigma2/settings/' restored.

**Comment by thawtes** [comment]
thank you

**Comment by iPkay** [comment]
No problem, I liked to do.
