### ISSUE TITLE
OpenATV 6.4 MetrixHD 1920x1080

### ISSUE THREAD

**Issue by vuplususer** [openatv/MetrixHD#396]
problem started from openatv-6.4_20191030_usb.zip update, yesterday I got different ERROR and I thought error are from plugin-feed and today got this ERROR: [create skin errno 17 file exists]

**Comment by iPkay** [comment]
Please try with new update or flash the new image. Alternativ: deinstall fhd icons and delete the 'FHD' folder in skin dir - now try again...

**Comment by vuplususer** [comment]
ok thanks I will try tonight

**Comment by vuplususer** [comment]
deleting files did not fix it I did flash new image

**Comment by Kramliraq** [comment]
Hello world
