### ISSUE TITLE
UHD icons missing countries folder, falls back to FHD

### ISSUE THREAD

**Issue by defkev** [openatv/MetrixHD#401]
Started recently after an online update (blue button)

> Error creating EHD-Skin. Some EHD-Icons are missing. Using HD-Skin!

Looking into `/usr/share/enigma2/MetrixHD/UHD` the `countries` folder is indeed missing.

Removing `enigma2-plugin-skins-metrix-atv-fhd-icons` and deleting the `FHD` folder does nothing as the fhd-icons package will be reinstalled when opening the MyMetrixLite settings.

Online flash (upgrade) will fix it till the next online update.

Box: Vu+ Solo 4k

**Comment by skubi23t** [comment]
I'm still having this issue on my vu+ 4k duo se - can't set the UHD icons enigma2-plugin-skins-metrix-atv-uhd-icons
