### ISSUE TITLE
Kanal# auf dem Display

### ISSUE THREAD

**Issue by abc29052019** [openatv/MetrixHD#407]
Hallo,
gibt es die Möglichkeit, das man die Kanalnummer auf dem Display dauerhaft einblendet, anstatt der Uhrzeit?
Box ist Amiko Viper Combo HDD mit openATV 6.4

Wäre eine tolle Ergänzung. Oder zumindest, wo ich es in den Skin-Dateien umändern muss?

**Comment by 4l3x2k** [comment]
Es gibt meiner Kenntnis nach keine Einstellung dafür.

Ich habe das mal auf einer SF8008 gemacht die genauso wie die Amiko Viper Combo HDD ein 7-Segment LCD hat.
Die Kanalnummer wird im Zustand Ein permanent angezeigt. Im Zustand Standby ist wieder die Uhr zu sehen.

Die verantwortliche Datei findest du auf der Box unter ```/usr/share/enigma2/display/skin_display.xml```.
Dort habe ich dann die Zeile 20 von
```
<convert type="VfdDisplay"></convert>
```
nach
```
<convert type="VfdDisplay">Number</convert>
```
geändert.

Bitte mache dir vorher ein Backup.
