### ISSUE TITLE
Infobar uncompleted

### ISSUE THREAD

**Issue by kingbecher** [openatv/MetrixHD#478]
Hi 

Im Using OPENATV 7.0 last update. Now i have the bug that the infoscreen is looking empty. No Second bar on top. Setting since the last update was same. If i deactivate the Channelnummer + name  everything works. But if you activate it the Screen becomes empty and still no Channelname + Number. You can look at my Picture of what i mean on  the Openatv forum. Link is https://www.opena.tv/skins/4708-metrixhd-standard-skin-openatv-185.html#post499548

Thanks. Hope for an fix because both of my Receivers with 7.0 has this issue (Octagon SF8008 , Vu+ Ultimo 4K)

**Comment by kingbecher** [comment]
Hello dear

I figured it out. 
My Channelslist how was corupt..

**Comment by nickersk** [comment]
thanks for the info, closing as resolved.
