### ISSUE TITLE
[MultiEPG] Zap icon broken

### ISSUE THREAD

**Issue by wedebe** [openatv/MetrixHD#514]
In the screenshot below:
- Frozen Planet II and Countryfile have `Zap` timers set (right-side half of timer icon shown for each)
- Saving Lives at Sea (left-side half of timer icon shown before, record icon shown for event, right-side half of timer icon shown after)

Default/initial settings in use.

![1_0_19_1B1C_802_2_11A0000_0_0_0_20221023011644](https://user-images.githubusercontent.com/9741693/197377846-e7f4087e-3b33-4ec2-bbea-52e83c34d5cd.jpg)

**Comment by jbleyel** [comment]
Have your zap timer a margin?
Can you try this zap timer again with 0 begin margin?

**Comment by wedebe** [comment]
> Have your zap timer a margin? Can you try this zap timer again with 0 begin margin?

0 mins margin before and after.

Issue only occurs when zap timer has an end time (default).

The following is what shows when a zap timer is edited to have no end time (separately, shouldn't this be default?)

**Comment by jbleyel** [comment]
-> https://github.com/openatv/enigma2/issues/2626

**Comment by wedebe** [comment]
Hi @jbleyel , this is still an issue with OATV7.0 20221118, using default settings (/etc/enigma2/settings deleted)

![1_0_19_5104_80F_2_11A0000_0_0_0_20221120095900-zap1](https://user-images.githubusercontent.com/9741693/202896522-4b0a6260-b649-4f38-8990-e7d669484664.jpg)

![1_0_19_5104_80F_2_11A0000_0_0_0_20221120095924-zap2](https://user-images.githubusercontent.com/9741693/202896524-2cb8838a-eb53-4389-ad4f-d80208d50d60.jpg)

![1_0_19_5104_80F_2_11A0000_0_0_0_20221120095942-zap3](https://user-images.githubusercontent.com/9741693/202896532-948ed2d2-0d0a-40c2-9734-f70a035ab52f.jpg)

**Comment by wedebe** [comment]
Confirmed fixed on OpenATV 7.1+
