### ISSUE TITLE
OpenAtv 7.3 FHD mode Skin Rendering issue

### ISSUE THREAD

**Issue by ruipisco** [openatv/MetrixHD#576]
Hi @jbleyel after updating OpenAtv 7.3 to the last update from 2023-07-06  (openatv-7.3-vuzero4k-20230706_usb.zip), the MyMetrixLite skin with FHD skin mode (1920x1080) in vuplus Zero 4K is not well formated and have a lot of parts that dosen't work, like the simple press on the "Menu" button that dosent show anything or it's too big that is not showed in the screen.
All items hare bigger, and need to revert to skin mode to 1280x720 to get the skin working again. COuld you please help solving this issue? Thanks!

**Comment by jbleyel** [comment]
Already fixed.
