### ISSUE TITLE
Event Text AutoScrool Issue in MyMetrixHD - OPEN ATV 7.4

### ISSUE THREAD

**Issue by ruipisco** [openatv/MetrixHD#610]
**To reproduce:**
Steps to reproduce the behavior of the Vertical AutoScrool in channel selection issue:

Click Up Arrow to go to the channel selection list.
Select an channel that has an event that haves an big text that cannot be displayed in the blue event box above the mini Tv.
See result/error on the text cannot deslocate from down to up to let the user read the event details.

**Screenshots**
<img width="854" alt="image_1" src="https://github.com/user-attachments/assets/d88e640b-77ae-4372-a724-e6344c6d554e">

**Image/Box Model (please complete the following information):**
Version: OpenAtv 7.4
BoxModel: VuPlus Zero 4K

**Additional context**
Looks like it's a bug in MetrixHDRunningText option when its activated the option Show Running Text = true in my metrix configuration settings.

**Comment by ruipisco** [comment]
@jbleyel can you help with this issue? it is with this bug ?

**Comment by jbleyel** [comment]
Should be fixed.
